export type Role = 'super_admin' | 'admin' | 'worker_standard' | 'worker_isolated' | 'accountant'
export type Stage = 'script' | 'voice' | 'editing' | 'publishing'
export type TaskStatus = 'pending' | 'in_progress' | 'review' | 'approved' | 'rejected'
export type Priority = 'low' | 'normal' | 'high' | 'urgent'

// profiles table — no email column, use auth.users for that
export interface Profile {
  id: string
  full_name: string | null
  avatar_url: string | null
  role: Role
  department: string | null
  is_active: boolean
  invited_by: string | null
  last_seen_at: string | null
  created_at: string
  updated_at: string
  // Injected from auth session (not a DB column):
  email?: string
}

// tasks table — NO status column; status lives in task_stages
export interface Task {
  id: string
  task_ref: string          // auto-generated by DB trigger (ZTV-NNN)
  title: string
  brief: string | null      // was called 'description' in spec but actual col is 'brief'
  priority: Priority
  current_stage: Stage
  publish_target: string[]
  assigned_to: string | null
  assigned_dept: string | null
  special_project_id: string | null
  deadline: string | null
  publish_at: string | null
  published_at: string | null
  publish_url: string | null
  is_overdue: boolean
  overdue_notified_at: string | null
  created_by: string
  created_at: string
  updated_at: string
  // Joined:
  assignee?: Profile | null
  task_stages?: TaskStage[]
  task_files?: TaskFile[]
}

// task_stages table
export interface TaskStage {
  id: string
  task_id: string
  stage: Stage
  assigned_to: string | null    // NOT assignee_id
  status: TaskStatus
  revision_num: number
  reject_reason: string | null
  approved_by: string | null
  started_at: string | null
  submitted_at: string | null
  approved_at: string | null
  rejected_at: string | null
  created_at: string
  // Joined:
  assignee?: Profile | null
}

// task_files table
export interface TaskFile {
  id: string
  task_id: string
  stage_id: string | null       // uuid FK to task_stages.id (NOT string stage name)
  category: string              // enum
  file_name: string             // NOT original_filename
  file_size_bytes: number
  provider: string              // enum: 'google_drive' | 'supabase_storage' | ...
  storage_key: string
  public_url: string | null
  mime_type: string
  uploaded_by: string
  is_deleted: boolean
  created_at: string
}

// activity_log table
export interface ActivityLog {
  id: string
  user_id: string
  task_id: string | null
  sp_id: string | null          // special project id
  action: string
  metadata: Record<string, unknown> | null
  created_at: string
  // Joined:
  user?: Profile | null
}

// special_projects table
export interface SpecialProject {
  id: string
  sp_ref: string                // auto-generated (SP-NNN)
  title: string
  description: string | null
  urgency: string               // NOT 'priority'
  status: string
  owner_id: string              // NOT NULL required field
  progress_pct: number
  started_at: string | null
  deadline: string | null
  completed_at: string | null
  publish_url: string | null
  publish_notes: string | null
  created_by: string
  created_at: string
  updated_at: string
}

// social_tasks table
export interface SocialTask {
  id: string
  sc_ref: string                // auto-generated (SC-NNN)
  task_type: string             // enum: 'caption' | 'post' | ...
  title: string
  brief: string | null
  platform: string[]
  parent_task_id: string | null
  parent_sp_id: string | null
  assigned_to: string | null
  priority: Priority
  status: TaskStatus
  content_draft: string | null
  content_final: string | null
  char_count: number | null
  submitted_at: string | null
  approved_by: string | null
  approved_at: string | null
  rejected_at: string | null
  reject_reason: string | null
  revision_num: number
  deadline: string | null
  is_overdue: boolean
  created_by: string
  created_at: string
  updated_at: string
  // Joined:
  assignee?: Profile | null
}

// notifications table
export interface Notification {
  id: string
  user_id: string
  title: string
  message: string
  read: boolean
  task_id: string | null
  created_at: string
}

// departments table
export interface Department {
  slug: string
  name: string
  description: string | null
  is_isolated: boolean
  color_hex: string
  display_order: number
  created_at: string
}

// ── Accounting Module ────────────────────────────────────────────
export type AccountingEntryStatus = 'pending' | 'approved' | 'rejected'
export type AccountingEntryType = 'debit' | 'credit'
export type AccountingCategoryType = 'expense' | 'asset' | 'payroll' | 'subscription' | 'per_diem' | 'operational' | 'revenue'

export interface AccountingCategory {
  id: string
  name: string
  type: AccountingCategoryType
  description: string | null
  created_at: string
}

export interface AccountingEntry {
  id: string
  reference_code: string
  title: string
  description: string | null
  amount: number
  currency: string
  category_id: string | null
  entry_type: AccountingEntryType
  status: AccountingEntryStatus
  submitted_by: string
  reviewed_by: string | null
  review_note: string | null
  entry_date: string
  created_at: string
  updated_at: string
  // Joined:
  category?: AccountingCategory | null
  submitter?: { full_name: string | null }
  reviewer?: { full_name: string | null }
}

export interface AccountingDocument {
  id: string
  entry_id: string
  file_name: string
  storage_key: string
  mime_type: string
  file_size_bytes: number | null
  uploaded_by: string
  created_at: string
}

export interface AccountingSummary {
  total_expenses: number
  total_credits: number
  pending_count: number
  total_assets: number
}

// ── Payroll Module ────────────────────────────────────────────────
export type PayrollStatus = 'pending' | 'approved' | 'paid' | 'rejected'

export interface PayrollEntry {
  id: string
  pr_ref: string
  employee_id: string | null
  employee_name: string
  department: string
  role_title: string | null
  gross_amount: number
  deductions: number
  net_amount: number
  status: PayrollStatus
  payment_month: string
  payment_date: string | null
  reject_reason: string | null
  notes: string | null
  created_by: string
  approved_by: string | null
  created_at: string
  updated_at: string
  // Joined:
  employee?: { full_name: string | null } | null
  creator?: { full_name: string | null }
  approver?: { full_name: string | null }
}

// Phase A update: status-gated totals — rejected entries NEVER in financial totals
export interface PayrollSummaryResult {
  // FINANCIAL TOTALS — approved + paid only
  total_gross: number
  total_deductions: number
  total_net: number
  // STATUS-SPLIT TOTALS — for dashboard cards
  approved_total: number     // approved only: committed, not yet paid
  paid_total: number         // paid only: finalized
  // COUNTS
  pending_count: number
  paid_count: number
  // AUDIT ONLY — never render in financial total cards
  rejected_total: number
  rejected_count: number
  // DEPARTMENT BREAKDOWN — approved + paid net only
  by_department: Record<string, number>
}

// Legacy type alias for backward compatibility during transition
export type PayrollSummary = PayrollSummaryResult
