'use client'
import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useUser } from '@/hooks/useUser'
import { useRouter } from 'next/navigation'
import { createTask } from '../actions'

type ProfileOption = { id: string; full_name: string | null; role: string }
type SPOption = { id: string; sp_ref: string; title: string }

const FIELD = {
  width: '100%', background: '#1A1A1A', border: '1px solid #2A2A2A',
  color: '#FFFFFF', fontFamily: "'IBM Plex Mono', monospace",
  fontSize: '0.85rem', padding: '0.75rem 1rem', outline: 'none', borderRadius: 0,
} as const

const LABEL = {
  display: 'block', fontFamily: "'IBM Plex Mono', monospace",
  fontSize: '0.65rem', color: '#888888', letterSpacing: '0.2em',
  textTransform: 'uppercase' as const, marginBottom: '0.4rem',
}

export default function NewTaskPage() {
  const { profile, isAdminOrAbove, isLoading } = useUser()
  const router = useRouter()
  const supabase = createClient()
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  const [profiles, setProfiles] = useState<ProfileOption[]>([])
  const [specialProjects, setSpecialProjects] = useState<SPOption[]>([])
  const [form, setForm] = useState({
    title: '',
    brief: '',
    current_stage: 'script',
    priority: 'normal',
    assigned_to: '',
    special_project_id: '',
    deadline: '',
    publish_target: [] as string[],
  })

  useEffect(() => {
    const fetchData = async () => {
      const [{ data: p }, { data: sp }] = await Promise.all([
        supabase.from('profiles').select('id,full_name,role').order('full_name'),
        supabase.from('special_projects').select('id,sp_ref,title').order('created_at', { ascending: false }),
      ])
      setProfiles((p || []) as ProfileOption[])
      setSpecialProjects((sp || []) as SPOption[])
    }
    fetchData()
  }, [])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!profile) return
    setSubmitting(true); setError('')

    try {
      // createTask server action uses admin client — bypasses broken SELECT RLS policy
      const result = await createTask({
        title: form.title,
        brief: form.brief || null,
        current_stage: form.current_stage,
        priority: form.priority,
        assigned_to: form.assigned_to || null,
        special_project_id: form.special_project_id || null,
        deadline: form.deadline ? new Date(form.deadline).toISOString() : null,
        publish_target: form.publish_target.length > 0 ? form.publish_target : ['youtube', 'instagram'],
        created_by: profile.id,
      })

      if ('error' in result) throw new Error(result.error)

      // Log activity (activity_log has no recursive RLS — browser client is fine)
      await supabase.from('activity_log').insert({
        task_id: result.id,
        user_id: profile.id,
        action: 'task_created',
        metadata: { task_ref: result.task_ref, title: form.title, user_name: profile.full_name },
      })

      setSuccess(`Task ${result.task_ref} created!`)
      setTimeout(() => router.push(`/tasks/${result.id}`), 1000)
    } catch (err: unknown) {
      setError((err as { message?: string }).message || 'Failed to create task')
    } finally {
      setSubmitting(false)
    }
  }

  const set = (k: string, v: string) => setForm(p => ({ ...p, [k]: v }))

  if (isLoading) return <div style={{ padding: '2rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>{[1,2,3].map(i => <div key={i} className="skeleton" style={{ height: '48px' }} />)}</div>

  if (!isAdminOrAbove) return <div style={{ padding: '2rem', fontFamily: "'IBM Plex Mono', monospace", fontSize: '0.85rem', color: '#888888' }}>Access denied. Only admins can create tasks.</div>

  return (
    <div style={{ padding: '1.5rem', maxWidth: '820px' }}>
      <div style={{ marginBottom: '1.5rem' }}>
        <h2 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: '2rem', letterSpacing: '0.08em', color: '#FFFFFF', margin: 0 }}>Create New Task</h2>
        <p style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: '0.75rem', color: '#888888', marginTop: '0.25rem' }}>Task reference (ZTV-NNN) is auto-generated by the system</p>
      </div>

      <form onSubmit={handleSubmit} data-testid="new-task-form" style={{ background: '#111111', border: '1px solid #2A2A2A', padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
        {/* Title */}
        <div>
          <label style={LABEL}>Task Title *</label>
          <input data-testid="task-title-input" type="text" required value={form.title} onChange={e => set('title', e.target.value)} placeholder="e.g. Presidential Address — Script Draft" style={FIELD} />
        </div>

        {/* Brief */}
        <div>
          <label style={LABEL}>Brief / Description</label>
          <textarea data-testid="task-brief-input" value={form.brief} onChange={e => set('brief', e.target.value)} placeholder="Task details, context, requirements..." rows={3} style={{ ...FIELD, resize: 'vertical' }} />
        </div>

        {/* Stage + Priority */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
          <div>
            <label style={LABEL}>Initial Stage</label>
            <select data-testid="task-stage-select" value={form.current_stage} onChange={e => set('current_stage', e.target.value)} style={{ ...FIELD, cursor: 'pointer' }}>
              {['script','voice','editing','publishing'].map(s => <option key={s} value={s}>{s.charAt(0).toUpperCase()+s.slice(1)}</option>)}
            </select>
          </div>
          <div>
            <label style={LABEL}>Priority</label>
            <div style={{ display: 'flex', gap: '0.5rem' }}>
              {['low','normal','high','urgent'].map(p => (
                <button key={p} type="button" data-testid={`priority-${p}`} onClick={() => set('priority', p)} style={{ flex: 1, padding: '0.65rem 0.25rem', fontFamily: "'IBM Plex Mono', monospace", fontSize: '0.6rem', letterSpacing: '0.1em', textTransform: 'uppercase', cursor: 'pointer', background: form.priority === p ? (p === 'urgent' ? '#CC1F1F' : p === 'high' ? '#F59E0B' : '#2A2A2A') : 'transparent', border: `1px solid ${form.priority === p ? (p === 'urgent' ? '#CC1F1F' : p === 'high' ? '#F59E0B' : '#888888') : '#2A2A2A'}`, color: form.priority === p ? '#FFFFFF' : '#888888', transition: 'all 150ms' }}>
                  {p}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Assignee + Deadline */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
          <div>
            <label style={LABEL}>Assign To</label>
            <select data-testid="task-assignee-select" value={form.assigned_to} onChange={e => set('assigned_to', e.target.value)} style={{ ...FIELD, cursor: 'pointer' }}>
              <option value="">— Unassigned —</option>
              {profiles.map(p => <option key={p.id} value={p.id}>{p.full_name || p.id.slice(0,8)}</option>)}
            </select>
          </div>
          <div>
            <label style={LABEL}>Deadline</label>
            <input data-testid="task-deadline-input" type="datetime-local" value={form.deadline} onChange={e => set('deadline', e.target.value)} style={{ ...FIELD, colorScheme: 'dark' }} />
          </div>
        </div>

        {/* Special Project */}
        <div>
          <label style={LABEL}>Link to Special Project (optional)</label>
          <select data-testid="task-sp-select" value={form.special_project_id} onChange={e => set('special_project_id', e.target.value)} style={{ ...FIELD, cursor: 'pointer' }}>
            <option value="">— None —</option>
            {specialProjects.map(sp => <option key={sp.id} value={sp.id}>{sp.sp_ref} — {sp.title}</option>)}
          </select>
        </div>

        {/* Publish Targets */}
        <div>
          <label style={LABEL}>Publish Targets</label>
          <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
            {['youtube','instagram','facebook','twitter','tiktok','website'].map(t => {
              const sel = form.publish_target.includes(t)
              return (
                <button key={t} type="button" onClick={() => setForm(prev => ({ ...prev, publish_target: sel ? prev.publish_target.filter(x => x !== t) : [...prev.publish_target, t] }))} style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: '0.65rem', letterSpacing: '0.1em', textTransform: 'uppercase', padding: '0.35rem 0.75rem', cursor: 'pointer', background: sel ? 'rgba(204,31,31,0.15)' : 'transparent', border: `1px solid ${sel ? '#CC1F1F' : '#2A2A2A'}`, color: sel ? '#FF2B2B' : '#888888', transition: 'all 150ms' }}>{t}</button>
              )
            })}
          </div>
        </div>

        {error && <div data-testid="form-error" style={{ background: 'rgba(204,31,31,0.1)', border: '1px solid rgba(204,31,31,0.4)', color: '#FF2B2B', fontFamily: "'IBM Plex Mono', monospace", fontSize: '0.75rem', padding: '0.6rem 1rem' }}>{error}</div>}
        {success && <div data-testid="form-success" style={{ background: 'rgba(34,197,94,0.1)', border: '1px solid rgba(34,197,94,0.4)', color: '#22C55E', fontFamily: "'IBM Plex Mono', monospace", fontSize: '0.75rem', padding: '0.6rem 1rem' }}>{success}</div>}

        <button type="submit" data-testid="submit-task-button" disabled={submitting}
          style={{ background: submitting ? '#1A0000' : '#CC1F1F', border: 'none', color: '#FFFFFF', fontFamily: "'Bebas Neue', sans-serif", fontSize: '1.1rem', letterSpacing: '0.15em', padding: '1rem', cursor: submitting ? 'not-allowed' : 'pointer', transition: 'background 150ms', marginTop: '0.5rem' }}
          onMouseEnter={e => { if (!submitting) (e.target as HTMLButtonElement).style.background = '#FF2B2B' }}
          onMouseLeave={e => { if (!submitting) (e.target as HTMLButtonElement).style.background = '#CC1F1F' }}
        >
          {submitting ? 'CREATING...' : 'CREATE TASK'}
        </button>
      </form>
    </div>
  )
}
