'use client'
import { useState } from 'react'
import { createSpecialProject, updateSpecialProject } from '@/app/(dashboard)/special-projects/actions'
import type { SpecialProject } from '@/types'

interface ProfileOption { id: string; full_name: string | null; role: string }

type Urgency = 'standard' | 'breaking' | 'high' | 'critical'
type SPStatus = 'draft' | 'active' | 'archived'

interface Props {
  project?: SpecialProject
  profiles: ProfileOption[]
  currentUserId: string
  onClose: () => void
  onSaved: (project: Partial<SpecialProject> & { id: string; sp_ref: string }) => void
}

const inputStyle: React.CSSProperties = {
  width: '100%',
  background: '#0A0A0A',
  border: '1px solid #2A2A2A',
  color: '#FFFFFF',
  fontFamily: "'IBM Plex Mono', monospace",
  fontSize: '0.8rem',
  padding: '0.65rem 0.85rem',
  borderRadius: 0,
  outline: 'none',
}

const labelStyle: React.CSSProperties = {
  display: 'block',
  fontFamily: "'IBM Plex Mono', monospace",
  fontSize: '0.6rem',
  color: '#888888',
  letterSpacing: '0.2em',
  textTransform: 'uppercase',
  marginBottom: '0.3rem',
}

const URGENCY_COLORS: Record<string, string> = { standard: '#888888', high: '#F59E0B', breaking: '#CC1F1F', critical: '#FF2B2B' }
const STATUS_COLORS: Record<string, string> = { draft: '#888888', active: '#22C55E', archived: '#6B7280' }

export function SPModal({ project, profiles, currentUserId, onClose, onSaved }: Props) {
  const isEdit = !!project
  const [title, setTitle] = useState(project?.title ?? '')
  const [description, setDescription] = useState(project?.description ?? '')
  const [ownerId, setOwnerId] = useState(project?.owner_id ?? currentUserId)
  const [urgency, setUrgency] = useState<Urgency>((project?.urgency as Urgency) ?? 'standard')
  const [status, setStatus] = useState<SPStatus>((project?.status as SPStatus) ?? 'draft')
  const [progressPct, setProgressPct] = useState(project?.progress_pct ?? 0)
  const [deadline, setDeadline] = useState(project?.deadline ? project.deadline.slice(0, 10) : '')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!title.trim() || title.trim().length < 3) { setError('Title must be at least 3 characters.'); return }
    if (!ownerId) { setError('Please select an owner.'); return }
    setLoading(true)
    setError('')

    const data = { title: title.trim(), description: description.trim(), owner_id: ownerId, urgency, status, progress_pct: progressPct, deadline: deadline || null }

    const result = isEdit
      ? await updateSpecialProject(project!.id, data)
      : await createSpecialProject({ ...data, created_by: currentUserId } as Parameters<typeof createSpecialProject>[0])

    setLoading(false)
    if (!result.success) { setError(result.error ?? 'Failed'); return }
    onSaved({
      id: result.id ?? project?.id ?? crypto.randomUUID(),
      sp_ref: result.sp_ref ?? project?.sp_ref ?? '',
      title: title.trim(),
      description: description.trim() || null,
      owner_id: ownerId,
      urgency,
      status,
      progress_pct: progressPct,
      deadline: deadline || null,
      created_by: project?.created_by ?? currentUserId,
      created_at: project?.created_at ?? new Date().toISOString(),
      updated_at: new Date().toISOString(),
    })
  }

  return (
    <div onClick={e => { if (e.target === e.currentTarget) onClose() }} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.88)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 9999, padding: '1rem' }}>
      <div data-testid="sp-modal" style={{ background: '#111111', border: '1px solid #2A2A2A', width: '100%', maxWidth: '520px', borderRadius: 0, maxHeight: '90vh', overflowY: 'auto' }}>
        {/* Header */}
        <div style={{ padding: '1.25rem 1.5rem', borderBottom: '1px solid #2A2A2A', display: 'flex', justifyContent: 'space-between', alignItems: 'center', position: 'sticky', top: 0, background: '#111111' }}>
          <div>
            <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: '1.3rem', letterSpacing: '0.1em', color: '#FFFFFF' }}>
              {isEdit ? `EDIT ${project!.sp_ref}` : 'NEW SPECIAL PROJECT'}
            </div>
            <div style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: '0.62rem', color: '#888888', marginTop: '0.1rem' }}>
              {isEdit ? 'Changes logged to activity_log' : 'sp_ref auto-generated by DB'}
            </div>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: '#888888', cursor: 'pointer', fontSize: '1.2rem', lineHeight: 1 }}>×</button>
        </div>

        <form onSubmit={handleSubmit} style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {/* Title */}
          <div>
            <label style={labelStyle} htmlFor="sp-title">Title *</label>
            <input id="sp-title" data-testid="sp-title-input" type="text" value={title} onChange={e => setTitle(e.target.value)} placeholder="Breaking: Nairobi Mayor announcement" maxLength={255} required style={inputStyle} />
          </div>

          {/* Description */}
          <div>
            <label style={labelStyle} htmlFor="sp-desc">Description</label>
            <textarea id="sp-desc" data-testid="sp-desc-input" value={description} onChange={e => setDescription(e.target.value)} placeholder="Context, scope, special instructions..." rows={3} maxLength={1000} style={{ ...inputStyle, resize: 'vertical', lineHeight: '1.5' }} />
          </div>

          {/* Owner */}
          <div>
            <label style={labelStyle} htmlFor="sp-owner">Owner / Assigned To *</label>
            <select id="sp-owner" data-testid="sp-owner-select" value={ownerId} onChange={e => setOwnerId(e.target.value)} style={{ ...inputStyle, cursor: 'pointer' }}>
              {profiles.map(p => (
                <option key={p.id} value={p.id}>{p.full_name || p.id} ({p.role})</option>
              ))}
            </select>
          </div>

          {/* Urgency + Status row */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
            <div>
              <label style={labelStyle} htmlFor="sp-urgency">Urgency</label>
              <select id="sp-urgency" data-testid="sp-urgency-select" value={urgency} onChange={e => setUrgency(e.target.value as Urgency)} style={{ ...inputStyle, cursor: 'pointer', color: URGENCY_COLORS[urgency] }}>
                {(['standard', 'high', 'breaking', 'critical'] as const).map(u => (
                  <option key={u} value={u} style={{ color: URGENCY_COLORS[u] }}>{u.toUpperCase()}</option>
                ))}
              </select>
            </div>
            <div>
              <label style={labelStyle} htmlFor="sp-status">Status</label>
              <select id="sp-status" data-testid="sp-status-select" value={status} onChange={e => setStatus(e.target.value as SPStatus)} style={{ ...inputStyle, cursor: 'pointer', color: STATUS_COLORS[status] }}>
                {(['draft', 'active', 'archived'] as const).map(s => (
                  <option key={s} value={s} style={{ color: STATUS_COLORS[s] }}>{s.toUpperCase()}</option>
                ))}
              </select>
            </div>
          </div>

          {/* Progress */}
          <div>
            <label style={{ ...labelStyle, marginBottom: '0.5rem' }}>Progress: {progressPct}%</label>
            <input data-testid="sp-progress-input" type="range" min={0} max={100} value={progressPct} onChange={e => setProgressPct(Number(e.target.value))} style={{ width: '100%', accentColor: '#CC1F1F' }} />
          </div>

          {/* Deadline */}
          <div>
            <label style={labelStyle} htmlFor="sp-deadline">Deadline (optional)</label>
            <input id="sp-deadline" data-testid="sp-deadline-input" type="date" value={deadline} onChange={e => setDeadline(e.target.value)} style={inputStyle} />
          </div>

          {error && (
            <div data-testid="sp-error" style={{ background: 'rgba(204,31,31,0.08)', border: '1px solid rgba(204,31,31,0.35)', color: '#FF2B2B', fontFamily: "'IBM Plex Mono', monospace", fontSize: '0.7rem', padding: '0.6rem 0.85rem' }}>
              {error}
            </div>
          )}

          <div style={{ display: 'flex', gap: '0.75rem', marginTop: '0.25rem' }}>
            <button type="button" onClick={onClose} style={{ flex: 1, background: '#1A1A1A', border: '1px solid #2A2A2A', color: '#888888', fontFamily: "'IBM Plex Mono', monospace", fontSize: '0.7rem', padding: '0.65rem', cursor: 'pointer', borderRadius: 0 }}>CANCEL</button>
            <button type="submit" data-testid="sp-submit-btn" disabled={loading} style={{ flex: 2, background: loading ? '#1A0000' : '#CC1F1F', border: 'none', color: '#FFFFFF', fontFamily: "'Bebas Neue', sans-serif", fontSize: '1rem', letterSpacing: '0.15em', padding: '0.65rem', cursor: loading ? 'not-allowed' : 'pointer', borderRadius: 0 }}>
              {loading ? 'SAVING...' : isEdit ? 'SAVE CHANGES' : 'CREATE PROJECT'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
